[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'AlessandroYorba/Alduin'
merged = 0

[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
  runtime macros/sandwich/keymap/surround.vim
'''

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'akiyan/vim-textobj-php'

[[plugins]]
repo = 'AndrewRadev/sideways.vim'
hook_add = '''
  nnoremap >, :SidewaysRight<CR>
  nnoremap <, :SidewaysLef<CR>
'''

[[plugins]]
repo = 'rickhowe/diffchar.vim'

[[plugins]]
repo = 'rickhowe/spotdiff.vim'

[[plugins]]
repo = 'ludovicchabant/vim-gutentags'
hook_add = '''
  let g:gutentags_modules = ['gtags_cscope']
  let g:gutentags_project_root = ['.projections.json']
  let g:gutentags_cache_dir = expand('~/.cache/tags')
'''

[[plugins]]
repo = 'skywind3000/gutentags_plus'

[[plugins]]
repo = 'tpope/vim-projectionist'

[[plugins]]
repo = 'jwalton512/vim-blade'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tyru/open-browser-github.vim'

[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = '''
  let g:startify_list_order = [
    \ ['🏁  セッション:'],
    \ 'sessions',
  \ ]
  let g:startify_session_persistence = 1
  let g:startify_custom_indices = ['s']

  autocmd User Startified setlocal buflisted
'''

[[plugins]]
repo = 'rhysd/git-messenger.vim'

[[plugins]]
repo = 'aperezdc/vim-template'
hook_add = '''
  let g:templates_directory = '~/.config/template/'
  let g:templates_no_builtin_templates = 1

  let g:templates_user_variables = [
  \   ['NAMESPACE', 'GetNameSpace'],
  \   ['USE', 'GetUse'],
  \   ['EXTENDS', 'GetExtends'],
  \ ]

  function! GetNameSpace()
    let s:composer_json_path = findfile('composer.json', '.;')
    let s:composer_json = json_decode(readfile(s:composer_json_path))

    let s:psr4_path_by_namespace = extend(
    \   get(get(s:composer_json, 'autoload', {}), 'psr-4', {}),
    \   get(get(s:composer_json, 'autoload-dev', {}), 'psr-4', {})
    \ )

    let s:fullpath = expand('%:p')
    let s:basepath = fnamemodify(s:composer_json_path, ':p:h')

    for [namespace, psr4_path] in items(s:psr4_path_by_namespace)
      if (stridx(s:fullpath, s:basepath .'/' . psr4_path) != -1)
        let s:splitted = split(s:fullpath, s:basepath . '/' . psr4_path)
        let s:relative_path_from_psr4_path = s:splitted[0]
        let s:relative_dir_from_psr4_path = fnamemodify(s:relative_path_from_psr4_path, ':h')
        if (s:relative_dir_from_psr4_path == '.' || s:relative_dir_from_psr4_path == '/')
          let s:replacedNamespace = substitute(namespace, '\', '\\\\', 'g')
          echom s:replacedNamespace
          return trim(s:replacedNamespace, '\')
        endif
        return namespace . '\' . substitute(s:relative_dir_from_psr4_path, '/', '\\\', 'g')
      endif
    endfor

    return ''
  endfunction

  function! GetExtends()
    let s:composer_json_path = findfile('composer.json', '.;')
    let s:fullpath = expand('%:p')
    let s:basepath = fnamemodify(s:composer_json_path, ':p:h')

    if (stridx(s:fullpath, s:basepath . '/tests') != -1)
      return ' extends TestCase'
    endif

    return ''
  endfunction

  function! GetUse()
    let s:composer_json_path = findfile('composer.json', '.;')
    let s:fullpath = expand('%:p')
    let s:basepath = fnamemodify(s:composer_json_path, ':p:h')

    if (stridx(s:fullpath, s:basepath . '/tests') != -1)
      return 'use PHPUnit\\Framework\\TestCase;'
    endif

    return ''
  endfunction
'''

[[plugins]]
repo = 'TaDaa/vimade'
hook_add = '''
  let g:vimade = {
  \   "fadelevel": 0.85
  \ }
'''

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'delphinus/vim-auto-cursorline'

[[plugins]]
repo = 'mechatroner/rainbow_csv'

[[plugins]]
repo = 'psliwka/vim-smoothie'
hook_add = '''
  let g:smoothie_base_speed = 17
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
if = '''executable('node') && executable('yarn')'''
rev = 'release'
hook_add = '''
  let g:coc_global_extensions = [
  \ "coc-actions",
  \ "coc-css",
  \ "coc-db",
  \ "coc-diagnostic",
  \ "coc-emmet",
  \ "coc-emoji",
  \ "coc-eslint",
  \ "coc-explorer",
  \ "coc-html",
  \ "coc-json",
  \ "coc-markdownlint",
  \ "coc-marketplace",
  \ "coc-pairs",
  \ "coc-phpls",
  \ "coc-post",
  \ "coc-sh",
  \ "coc-solargraph",
  \ "coc-snippets",
  \ "coc-spell-checker",
  \ "coc-solargraph",
  \ "coc-stylelintplus",
  \ "coc-tabnine",
  \ "coc-translator",
  \ "coc-tsserver",
  \ "coc-vetur",
  \ "https://github.com/h4kst3r/php-awesome-snippets",
  \ ]

  let g:coc_filetype_map = {
  \ 'php.phpunit': 'php'
  \ }

  function! GoToDefinition() abort
    if CocAction('jumpDefinition')
	  return v:true
	endif

	execute("silent! tag " . expand("<cword>"))
  endfunction

  xnoremap <silent> <leader>a  :<C-u>execute 'CocCommand actions.open ' . visualmode()<CR>
  nnoremap <silent> <leader>a  :<C-u>set operatorfunc=<SID>cocActionsOpenFromSelected<CR>g@
  nnoremap <silent> <leader>e  :<C-u>CocCommand explorer<CR>
  nnoremap <silent> <C-]>      :<C-u>call GoToDefinition()<CR>
  nnoremap <silent> <C-w><C-]> :call CocAction('jumpDefinition', 'vsplit')<CR>
  nmap     <silent> <C-[>      <Plug>(coc-references)
  nnoremap <silent> <leader>ch :<C-u>call CocActionAsync('doHover')<CR>
  nmap     <silent> <leader>cr <Plug>(coc-refactor)
  nmap     <silent> <leader>cn <Plug>(coc-rename)
  nmap     <silent> <leader>cd <Plug>(coc-declaration)
  nmap     <silent> <leader>ct <Plug>(coc-type-definition)
  nmap     <silent> <leader>ci <Plug>(coc-implementation)
  nnoremap <silent> <leader>cs :<C-u>CocList -I symbols<CR>
  nmap     <silent> <C-t>      <Plug>(coc-translator-p)
  vnoremap <silent> <C-t>      "zy:CocCommand translator.popup <C-r>z<CR>

  inoremap <silent><expr> <TAB>
    \ pumvisible() ? coc#_select_confirm() :
	\ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump', ''])\<CR>" :
	\ <SID>check_back_space() ? "\<TAB>" :
	\ coc#refresh()

  function! s:check_back_space() abort
    let col = col('.') - 1
	return !col || getline('.')[col - 1] =~# '\s'
  endfunction

  let g:coc_snippet_next = '<tab>'
  autocmd CursorHold * silent call CocActionAsync('highlight')
'''

[plugins.ftplugin]
post = '''
  set syntax=yaml
  nmap <silent><buffer> <leader><leader> :<C-u>CocCommand post.do<CR>
'''

log = '''
  set syntax=yaml
'''
