#!/usr/bin/env bash

DOTFILES_REPOSITORY_DIR=~/.dotfiles
DOTFILES_REPOSITORY_URL="https://github.com/ymap/dotfiles.git"

if [ -d $DOTFILES_REPOSITORY_DIR ]; then
  echo "$DOTFILES_REPOSITORY_DIR: directory already exists"
  exit 1
fi



ln -s "$DOTFILES_REPOSITORY_DIR/.vim" "$HOME/.vim"
ln -s "$DOTFILES_REPOSITORY_DIR/.config" "$HOME/.config"
