#!/usr/bin/env bash

DOTFILES_REPOSITORY_DIR=~/.dotfiles
DOTFILES_REPOSITORY_URL="https://github.com/ymap/dotfiles.git"

if !(type brew >/dev/null 2>&1); then
  if [ "$(uname)" == "Darwin" ]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  fi
fi

if [ -d $DOTFILES_REPOSITORY_DIR ]; then
  echo "$DOTFILES_REPOSITORY_DIR: directory already exists"
  exit 1
fi


if !(type git >/dev/null 2>&1); then
  brew install git
fi

git clone "$DOTFILES_REPOSITORY_URL" "$DOTFILES_REPOSITORY_DIR"

ln -s "$DOTFILES_REPOSITORY_DIR/.vim" "$HOME/.vim"
ln -s "$DOTFILES_REPOSITORY_DIR/.config" "$HOME/.config"
